In [2]:
import pandas as pd

df = pd.read_csv (r'C:\Users\PC\Desktop\FAX\4\strojno učenje\Moneyball-master\data\main_players.csv')   #read the csv file (put 'r' before the path string to address any special characters, such as '\'). Don't forget to put the file name at the end of the path + ".csv"
print (df)


       Unnamed: 0      ID                Name  Age  \
0               0  158023            L. Messi   31   
1               1  190871           Neymar Jr   26   
2               2  177003           L. Modrić   32   
3               3  176580           L. Suárez   31   
4               4  155862        Sergio Ramos   32   
5               5  188545      R. Lewandowski   29   
6               6  182493            D. Godín   32   
7               7  168542         David Silva   32   
8               8  215914            N. Kanté   27   
9               9  211110           P. Dybala   24   
10             10  202126             H. Kane   24   
11             11  194765        A. Griezmann   27   
12             12  189511     Sergio Busquets   29   
13             13  179813           E. Cavani   31   
14             14  153079           S. Agüero   30   
15             15  138956        G. Chiellini   33   
16             16  231747           K. Mbappé   19   
17             17  209331   

In [3]:
primjer10=df[:10]
print(primjer10)

   Unnamed: 0      ID            Name  Age  \
0           0  158023        L. Messi   31   
1           1  190871       Neymar Jr   26   
2           2  177003       L. Modrić   32   
3           3  176580       L. Suárez   31   
4           4  155862    Sergio Ramos   32   
5           5  188545  R. Lewandowski   29   
6           6  182493        D. Godín   32   
7           7  168542     David Silva   32   
8           8  215914        N. Kanté   27   
9           9  211110       P. Dybala   24   

                                            Photo Nationality  \
0  https://cdn.sofifa.org/players/4/19/158023.png   Argentina   
1  https://cdn.sofifa.org/players/4/19/190871.png      Brazil   
2  https://cdn.sofifa.org/players/4/19/177003.png     Croatia   
3  https://cdn.sofifa.org/players/4/19/176580.png     Uruguay   
4  https://cdn.sofifa.org/players/4/19/155862.png       Spain   
5  https://cdn.sofifa.org/players/4/19/188545.png      Poland   
6  https://cdn.sofifa.org/players/4/19

In [4]:
import numpy as np
X_10=primjer10.iloc[:,28:87]
X0=np.ones((10,1))
X_10=np.hstack((X0,X_10))
print(X_10)

[[ 1. 88. 88. 88. 92. 93. 93. 93. 92. 93. 93. 93. 91. 84. 84. 84. 91. 64.
  61. 61. 61. 64. 59. 47. 47. 47. 59. 84. 95. 70. 90. 86. 97. 93. 94. 87.
  96. 91. 86. 91. 95. 95. 85. 68. 72. 59. 94. 48. 22. 94. 94. 75. 96. 33.
  28. 26.  6. 11. 15. 14.]
 [ 1. 84. 84. 84. 89. 89. 89. 89. 89. 89. 89. 89. 88. 81. 81. 81. 88. 65.
  60. 60. 60. 65. 60. 47. 47. 47. 60. 79. 87. 62. 84. 84. 96. 88. 87. 78.
  95. 94. 90. 96. 94. 84. 80. 61. 81. 49. 82. 56. 36. 89. 87. 81. 94. 27.
  24. 33.  9.  9. 15. 15.]
 [ 1. 77. 77. 77. 85. 84. 84. 84. 85. 87. 87. 87. 86. 88. 88. 88. 86. 82.
  81. 81. 81. 82. 79. 71. 71. 71. 79. 86. 72. 55. 93. 76. 90. 85. 78. 88.
  93. 80. 72. 93. 90. 94. 79. 68. 89. 58. 82. 62. 83. 79. 92. 82. 84. 60.
  76. 73. 13.  9.  7. 14.]
 [ 1. 87. 87. 87. 86. 87. 87. 87. 86. 85. 85. 85. 84. 79. 79. 79. 84. 69.
  68. 68. 68. 69. 66. 63. 63. 63. 66. 77. 93. 77. 82. 88. 87. 86. 84. 64.
  90. 86. 75. 82. 92. 83. 86. 69. 90. 83. 85. 87. 41. 92. 84. 85. 85. 62.
  45. 38. 27. 25. 31. 33.]
 [ 1

In [7]:
Y_10 = primjer10.iloc[:,7]
Y_10=Y_10.values

print(Y_10)

[94 92 91 91 91 90 90 90 89 89]


In [9]:
Y_10.shape

(10,)

In [10]:
print(X_10)

[[ 1. 88. 88. 88. 92. 93. 93. 93. 92. 93. 93. 93. 91. 84. 84. 84. 91. 64.
  61. 61. 61. 64. 59. 47. 47. 47. 59. 84. 95. 70. 90. 86. 97. 93. 94. 87.
  96. 91. 86. 91. 95. 95. 85. 68. 72. 59. 94. 48. 22. 94. 94. 75. 96. 33.
  28. 26.  6. 11. 15. 14.]
 [ 1. 84. 84. 84. 89. 89. 89. 89. 89. 89. 89. 89. 88. 81. 81. 81. 88. 65.
  60. 60. 60. 65. 60. 47. 47. 47. 60. 79. 87. 62. 84. 84. 96. 88. 87. 78.
  95. 94. 90. 96. 94. 84. 80. 61. 81. 49. 82. 56. 36. 89. 87. 81. 94. 27.
  24. 33.  9.  9. 15. 15.]
 [ 1. 77. 77. 77. 85. 84. 84. 84. 85. 87. 87. 87. 86. 88. 88. 88. 86. 82.
  81. 81. 81. 82. 79. 71. 71. 71. 79. 86. 72. 55. 93. 76. 90. 85. 78. 88.
  93. 80. 72. 93. 90. 94. 79. 68. 89. 58. 82. 62. 83. 79. 92. 82. 84. 60.
  76. 73. 13.  9.  7. 14.]
 [ 1. 87. 87. 87. 86. 87. 87. 87. 86. 85. 85. 85. 84. 79. 79. 79. 84. 69.
  68. 68. 68. 69. 66. 63. 63. 63. 66. 77. 93. 77. 82. 88. 87. 86. 84. 64.
  90. 86. 75. 82. 92. 83. 86. 69. 90. 83. 85. 87. 41. 92. 84. 85. 85. 62.
  45. 38. 27. 25. 31. 33.]
 [ 1

In [11]:
print(X_10)               
print(type(X_10)) 

[[ 1. 88. 88. 88. 92. 93. 93. 93. 92. 93. 93. 93. 91. 84. 84. 84. 91. 64.
  61. 61. 61. 64. 59. 47. 47. 47. 59. 84. 95. 70. 90. 86. 97. 93. 94. 87.
  96. 91. 86. 91. 95. 95. 85. 68. 72. 59. 94. 48. 22. 94. 94. 75. 96. 33.
  28. 26.  6. 11. 15. 14.]
 [ 1. 84. 84. 84. 89. 89. 89. 89. 89. 89. 89. 89. 88. 81. 81. 81. 88. 65.
  60. 60. 60. 65. 60. 47. 47. 47. 60. 79. 87. 62. 84. 84. 96. 88. 87. 78.
  95. 94. 90. 96. 94. 84. 80. 61. 81. 49. 82. 56. 36. 89. 87. 81. 94. 27.
  24. 33.  9.  9. 15. 15.]
 [ 1. 77. 77. 77. 85. 84. 84. 84. 85. 87. 87. 87. 86. 88. 88. 88. 86. 82.
  81. 81. 81. 82. 79. 71. 71. 71. 79. 86. 72. 55. 93. 76. 90. 85. 78. 88.
  93. 80. 72. 93. 90. 94. 79. 68. 89. 58. 82. 62. 83. 79. 92. 82. 84. 60.
  76. 73. 13.  9.  7. 14.]
 [ 1. 87. 87. 87. 86. 87. 87. 87. 86. 85. 85. 85. 84. 79. 79. 79. 84. 69.
  68. 68. 68. 69. 66. 63. 63. 63. 66. 77. 93. 77. 82. 88. 87. 86. 84. 64.
  90. 86. 75. 82. 92. 83. 86. 69. 90. 83. 85. 87. 41. 92. 84. 85. 85. 62.
  45. 38. 27. 25. 31. 33.]
 [ 1

In [12]:
n=len(X_10[0])
print(n)

60


In [13]:
theta = np.zeros(shape=(n,1))
print(theta)

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]


In [22]:
a=np.dot(X_10.T,X_10)
ainv=np.linalg.pinv(a)
b=np.dot(ainv,X_10.T)
t=np.dot(b,Y_10)

#a.shape
#inv.shape
#b.shape
t.shape

(60,)

In [15]:
print(Y_10)

[94 92 91 91 91 90 90 90 89 89]


In [16]:
print(t)

[ 0.00132055  0.02281627  0.02281627  0.02281627  0.03420382  0.02598062
  0.02598062  0.02598062  0.03420382  0.02965308  0.02965308  0.02965308
  0.03095578  0.03614735  0.03614735  0.03614735  0.03095578  0.0234714
  0.02381397  0.02381397  0.02381397  0.0234714   0.01455863  0.0265121
  0.0265121   0.0265121   0.01455863  0.04173281 -0.07154821  0.10318554
  0.10659162  0.00020095  0.0329532  -0.00446002 -0.00424436  0.0254927
  0.08683149  0.0364571   0.03506691 -0.00674196  0.09533057 -0.06633813
 -0.00446964  0.03479357 -0.05796823  0.03108853 -0.07176529  0.02564681
  0.02720483 -0.00146959  0.00538857 -0.00950707  0.11488213 -0.01296491
 -0.06399918 -0.01077933 -0.04473691  0.00350514  0.05634316  0.00831911]


In [17]:
t.shape

(60,)

In [18]:
#gradijent:

In [19]:
J=(np.dot(X_10,theta)-Y_10)^2 /(2*10) #tu nekaj neš ne štima

TypeError: ufunc 'bitwise_xor' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [20]:
alfa=1
for i=1:20
    theta=theta-(alfa/10)*np.dot((np.dot(X_10,theta)-Y_10),X_10)
    end for

SyntaxError: invalid syntax (<ipython-input-20-ebef7dfb07c4>, line 2)

In [ ]:
#treba dodati feature scaling za par featura
#usporedi gradijent

In [ ]:
#gradijent za svaki skup
#usporedba
#mean error