In [7]:
from google.colab import files
uploaded = files.upload()

Saving main_players.csv to main_players (1).csv


In [0]:
import json
import os
import csv
import collections
import numpy as np
import pandas as pd
import keras
import tensorflow as tf
import shutil
import time
from scipy.stats import zscore
from scipy import stats
from sklearn import preprocessing
from sklearn import utils
import sklearn.feature_extraction.text as sk_text
from sklearn.model_selection import train_test_split
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression, Ridge, RidgeCV, Lasso, ElasticNet
from sklearn.ensemble import GradientBoostingRegressor

import io
import requests
from sklearn import metrics
from keras import optimizers
from keras.optimizers import Adam, sgd
from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D
from keras.layers.core import Dense, Activation, Dropout, Flatten
from keras.callbacks import EarlyStopping, ModelCheckpoint
import xgboost as xgb
import lightgbm as lgb



In [0]:
# Encode text values to dummy variables(i.e. [1,0,0],[0,1,0],[0,0,1] for red,green,blue)
def encode_text_dummy(df, name):
    dummies = pd.get_dummies(df[name])
    for x in dummies.columns:
        dummy_name = "{}-{}".format(name, x)
        df[dummy_name] = dummies[x]
    df.drop(name, axis=1, inplace=True)


# Encode text values to indexes(i.e. [1],[2],[3] for red,green,blue).
def encode_text_index(df, name):
    le = preprocessing.LabelEncoder()
    df[name] = le.fit_transform(df[name])
    return le.classes_


# Encode a numeric column as zscores
def encode_numeric_zscore(df, name, mean=None, sd=None):
    if mean is None:
        mean = df[name].mean()

    if sd is None:
        sd = df[name].std()

    df[name] = (df[name] - mean) / sd


# Convert all missing values in the specified column to the median
def missing_median(df, name):
    med = df[name].median()
    df[name] = df[name].fillna(med)


# Convert all missing values in the specified column to the default
def missing_default(df, name, default_value):
    df[name] = df[name].fillna(default_value)


# Convert a Pandas dataframe to the x,y inputs that TensorFlow needs
def to_xy(df, target):
    result = []
    for x in df.columns:
        if x != target:
            result.append(x)
    # find out the type of the target column. 
    target_type = df[target].dtypes
    target_type = target_type[0] if isinstance(target_type, collections.Sequence) else target_type
    # Encode to int for classification, float otherwise. TensorFlow likes 32 bits.
    if target_type in (np.int64, np.int32, np.object):
        # Classification
        dummies = pd.get_dummies(df[target])
        return df[result].values.astype(np.float32), dummies.values.astype(np.float32)
    else:
        # Regression
        return df[result].values.astype(np.float32), df[target].values.astype(np.float32)

# Nicely formatted time string
def hms_string(sec_elapsed):
    h = int(sec_elapsed / (60 * 60))
    m = int((sec_elapsed % (60 * 60)) / 60)
    s = sec_elapsed % 60
    return "{}:{:>02}:{:>05.2f}".format(h, m, s)


# Regression chart.
def chart_regression(pred,y,sort=True):
    t = pd.DataFrame({'pred' : pred, 'y' : y.flatten()})
    if sort:
        t.sort_values(by=['y'],inplace=True)
    a = plt.plot(t['y'].tolist(),label='expected')
    b = plt.plot(t['pred'].tolist(),label='prediction')
    plt.ylabel('output')
    plt.legend()
    plt.show()

# Remove all rows where the specified column is +/- sd standard deviations
def remove_outliers(df, name, sd):
    drop_rows = df.index[(np.abs(df[name] - df[name].mean()) >= (sd * df[name].std()))]
    df.drop(drop_rows, axis=0, inplace=True)


# Encode a column to a range between normalized_low and normalized_high.
def encode_numeric_range(df, name, normalized_low=0, normalized_high=1,
                         data_low=None, data_high=None):
    if data_low is None:
        data_low = min(df[name])
        data_high = max(df[name])

    df[name] = ((df[name] - data_low) / (data_high - data_low)) \
               * (normalized_high - normalized_low) + normalized_low

In [0]:
df =pd.read_csv('main_players.csv')

In [0]:
df.drop(['Unnamed: 0','Photo','Flag','Club Logo'],axis=1,inplace=True)

In [0]:
df['ShortPassing'].fillna(df['ShortPassing'].mean(), inplace = True)
df['Volleys'].fillna(df['Volleys'].mean(), inplace = True)
df['Dribbling'].fillna(df['Dribbling'].mean(), inplace = True)
df['Curve'].fillna(df['Curve'].mean(), inplace = True)
df['FKAccuracy'].fillna(df['FKAccuracy'], inplace = True)
df['LongPassing'].fillna(df['LongPassing'].mean(), inplace = True)
df['BallControl'].fillna(df['BallControl'].mean(), inplace = True)
df['HeadingAccuracy'].fillna(df['HeadingAccuracy'].mean(), inplace = True)
df['Finishing'].fillna(df['Finishing'].mean(), inplace = True)
df['Crossing'].fillna(df['Crossing'].mean(), inplace = True)
df['Weight'].fillna('200lbs', inplace = True)
df['Contract Valid Until'].fillna(2019, inplace = True)
df['Height'].fillna("5'11", inplace = True)
df['Loaned From'].fillna('None', inplace = True)
df['Joined'].fillna('Jul 1, 2018', inplace = True)
df['Jersey Number'].fillna(8, inplace = True)
df['Body Type'].fillna('Normal', inplace = True)
df['Position'].fillna('ST', inplace = True)
df['Club'].fillna('No Club', inplace = True)
df['Work Rate'].fillna('Medium/ Medium', inplace = True)
df['Skill Moves'].fillna(df['Skill Moves'].median(), inplace = True)
df['Weak Foot'].fillna(3, inplace = True)
df['Preferred Foot'].fillna('Right', inplace = True)
df['International Reputation'].fillna(1, inplace = True)
df['Wage'].fillna('€200K', inplace = True)

In [15]:
df.dropna()

ID                Name  Age  ... GKReflexes  Release Clause  pozicija
0      158023            L. Messi   31  ...          8         €226.5M         N
1      190871           Neymar Jr   26  ...         11         €228.1M         N
2      177003           L. Modrić   32  ...          9         €137.4M         V
3      176580           L. Suárez   31  ...         37           €164M         N
4      155862        Sergio Ramos   32  ...         11         €104.6M         B
5      188545      R. Lewandowski   29  ...         10         €127.1M         N
6      182493            D. Godín   32  ...         15          €90.2M         B
7      168542         David Silva   32  ...         12           €111M         V
8      215914            N. Kanté   27  ...         10         €121.3M         V
9      211110           P. Dybala   24  ...          8         €153.5M         N
10     202126             H. Kane   24  ...         11         €160.7M         N
11     194765        A. Griezmann   27  ...         14         €165.8M         V
12     189511     Sergio Busquets   29  ...         13         €105.6M         V
13     179813           E. Cavani   31  ...         10           €111M         N
14     153079           S. Agüero   30  ...         14         €119.3M         N
15     138956        G. Chiellini   33  ...          3          €44.6M         B
16     231747           K. Mbappé   19  ...          6         €166.1M         V
17     209331            M. Salah   26  ...         14         €137.3M         V
18     200145            Casemiro   26  ...         12         €126.4M         V
20     198219          L. Insigne   27  ...         10         €105.4M         N
21     197781                Isco   26  ...          6         €156.2M         N
22     190460          C. Eriksen   26  ...          6         €141.5M         V
23     189242            Coutinho   26  ...          6         €147.7M         N
24     188567       P. Aubameyang   29  ...          9         €112.1M         V
25     178603          M. Hummels   29  ...          6          €75.9M         B
26     173731             G. Bale   28  ...          6           €123M         N
28     164240        Thiago Silva   33  ...         10          €44.4M         B
29     205600           S. Umtiti   24  ...         15         €121.1M         B
30     201399           M. Icardi   25  ...          9         €114.5M         N
31     201024        K. Koulibaly   27  ...          5          €90.5M         B
...       ...                 ...  ...  ...        ...             ...       ...
12850  243876   M. Frøkjær-Jensen   18  ...         11           €113K         V
12851  245412           H. Norris   17  ...         11           €119K         B
12852  243621            N. Ayéva   16  ...          6           €158K         N
12853  243112              Wu Lei   21  ...          5            €94K         V
12854  245417           J. Manley   19  ...          5            €70K         B
12855  246447     Nicolas Firmino   17  ...         12           €147K         V
12856  237746         Y. Uchimura   33  ...         15            €25K         V
12857  238520            R. Takae   20  ...          8           €113K         V
12858  243900          S. Adewusi   18  ...         12           €143K         V
12859  243649           E. Clarke   19  ...          7            €78K         B
12860  246227          T. Hillman   17  ...          8            €78K         V
12861  238550           R. Roache   18  ...         12           €193K         N
12862  246243         J. Williams   17  ...          8           €119K         B
12863  245734            C. Maher   17  ...         10           €109K         B
12864  243961            E. Tweed   19  ...          8            €88K         V
12865  240917        Zhang Yufeng   20  ...          8           €167K         V
12866  240158           C. Ehlich   19  ...         12            €66K         B
12867  240160          A. Kaltner   18  ..

In [0]:
col = ['Age', 'Potential', 'Crossing', 'Finishing', 'HeadingAccuracy', 'ShortPassing', 'Volleys', 'Dribbling', 'Curve', 'FKAccuracy', 'LongPassing', 'BallControl', 'Acceleration', 'SprintSpeed', 'Agility', 'Reactions', 'Balance', 'ShotPower', 'Jumping' ,'Stamina', 'Strength', 'LongShots', 'Aggression', 'Interceptions', 'Positioning' ,'Vision', 'Penalties', 'Composure', 'Marking', 'StandingTackle', 'SlidingTackle', 'GKDiving', 'GKHandling', 'GKKicking', 'GKPositioning', 'GKReflexes']

for x in col:
    encode_numeric_range(df,x)

In [17]:
#Label encoding

encode_text_index(df,'Preferred Foot')
encode_text_index(df,'Body Type')

array(['Akinfenwa', 'Lean', 'Messi', 'Neymar', 'Normal',
       'PLAYER_BODY_TYPE_25', 'Shaqiri', 'Stocky'], dtype=object)

In [19]:
df.columns

Index(['ID', 'Name', 'Age', 'Nationality', 'Overall', 'Potential', 'Club',
       'Value', 'Wage', 'Special', 'Preferred Foot',
       'International Reputation', 'Weak Foot', 'Skill Moves', 'Work Rate',
       'Body Type', 'Real Face', 'Position', 'Jersey Number', 'Joined',
       'Loaned From', 'Contract Valid Until', 'Height', 'Weight', 'LS', 'ST',
       'RS', 'LW', 'LF', 'CF', 'RF', 'RW', 'LAM', 'CAM', 'RAM', 'LM', 'LCM',
       'CM', 'RCM', 'RM', 'LWB', 'LDM', 'CDM', 'RDM', 'RWB', 'LB', 'LCB', 'CB',
       'RCB', 'RB', 'Crossing', 'Finishing', 'HeadingAccuracy', 'ShortPassing',
       'Volleys', 'Dribbling', 'Curve', 'FKAccuracy', 'LongPassing',
       'BallControl', 'Acceleration', 'SprintSpeed', 'Agility', 'Reactions',
       'Balance', 'ShotPower', 'Jumping', 'Stamina', 'Strength', 'LongShots',
       'Aggression', 'Interceptions', 'Positioning', 'Vision', 'Penalties',
       'Composure', 'Marking', 'StandingTackle', 'SlidingTackle', 'GKDiving',
       'GKHandling', 'GKKicking

In [0]:
df.dropna(inplace = True)

In [0]:
col = ['Age', 'Potential', 'Crossing', 'Finishing', 'HeadingAccuracy', 'ShortPassing', 'Volleys', 'Dribbling', 'Curve', 'FKAccuracy', 'LongPassing', 'BallControl', 'Acceleration', 'SprintSpeed', 'Agility', 'Reactions', 'Balance', 'ShotPower', 'Jumping' ,'Stamina', 'Strength', 'LongShots', 'Aggression', 'Interceptions', 'Positioning' ,'Vision', 'Penalties', 'Composure', 'Marking', 'StandingTackle', 'SlidingTackle', 'GKDiving', 'GKHandling', 'GKKicking', 'GKPositioning', 'GKReflexes']

for x in col:
    remove_outliers(df,x,3)

In [0]:
df_x = df[['Age','Potential', 'Crossing', 'Finishing', 'HeadingAccuracy', 'ShortPassing', 'Volleys', 'Dribbling', 'Curve', 'FKAccuracy', 'LongPassing', 'BallControl', 'Acceleration', 'SprintSpeed', 'Agility', 'Reactions', 'Balance', 'ShotPower', 'Jumping' ,'Stamina', 'Strength', 'LongShots', 'Aggression', 'Interceptions', 'Positioning' ,'Vision', 'Penalties', 'Composure', 'Marking', 'StandingTackle', 'SlidingTackle', 'GKDiving', 'GKHandling', 'GKKicking', 'GKPositioning', 'GKReflexes', 'Preferred Foot', 'Body Type']].copy()

In [23]:
df_x

Age  Potential  Crossing  ...  GKReflexes  Preferred Foot  Body Type
12     0.52   0.872340  0.629630  ...    0.333333               1          1
15     0.68   0.872340  0.580247  ...    0.055556               0          4
24     0.52   0.851064  0.814815  ...    0.222222               1          1
26     0.48   0.851064  0.938272  ...    0.138889               0          1
28     0.68   0.851064  0.604938  ...    0.250000               1          4
32     0.48   0.829787  0.543210  ...    0.138889               1          4
33     0.52   0.829787  0.938272  ...    0.333333               0          4
34     0.60   0.829787  0.814815  ...    0.083333               1          4
35     0.60   0.829787  0.703704  ...    0.166667               0          4
36     0.56   0.829787  0.827160  ...    0.361111               1          4
37     0.56   0.829787  0.901235  ...    0.222222               1          4
38     0.60   0.829787  0.567901  ...    0.194444               1          4
41     0.40   0.829787  0.765432  ...    0.361111               1          1
42     0.40   0.851064  0.518519  ...    0.277778               1          4
43     0.28   0.872340  0.814815  ...    0.222222               1          1
44     0.40   0.829787  0.753086  ...    0.250000               1          1
47     0.44   0.808511  0.901235  ...    0.111111               0          4
49     0.44   0.808511  0.753086  ...    0.333333               1          4
50     0.52   0.808511  0.839506  ...    0.277778               1          1
51     0.48   0.808511  0.864198  ...    0.111111               1          4
52     0.60   0.808511  0.407407  ...    0.083333               1          1
53     0.52   0.829787  0.654321  ...    0.361111               1          4
55     0.60   0.808511  0.419753  ...    0.277778               1          4
56     0.68   0.808511  0.703704  ...    0.166667               1          1
59     0.32   0.872340  0.888889  ...    0.388889               0          7
60     0.28   0.851064  0.975309  ...    0.388889               1          1
62     0.44   0.787234  0.864198  ...    0.138889               0          1
63     0.44   0.808511  0.654321  ...    0.138889               1          4
64     0.56   0.787234  0.506173  ...    0.305556               1          4
65     0.52   0.787234  0.901235  ...    0.194444               1          1
...     ...        ...       ...  ...         ...             ...        ...
12841  0.04   0.468085  0.308642  ...    0.361111               1          1
12842  0.16   0.234043  0.345679  ...    0.111111               0          1
12843  0.12   0.340426  0.308642  ...    0.111111               1          1
12844  0.12   0.297872  0.320988  ...    0.138889               1          1
12845  0.08   0.382979  0.246914  ...    0.194444               1          4
12846  0.08   0.255319  0.283951  ...    0.305556               1          1
12847  0.04   0.319149  0.345679  ...    0.194444               0          4
12848  0.08   0.212766  0.382716  ...    0.166667               1          4
12849  0.00   0.382979  0.358025  ...    0.138889               1          1
12850  0.08   0.319149  0.320988  ...    0.277778               1          4
12852  0.00   0.510638  0.283951  ...    0.138889               1          4
12853  0.20   0.212766  0.506173  ...    0.111111               1          7
12855  0.04   0.468085  0.246914  ...    0.305556               1          1
12857  0.16   0.319149  0.333333  ...    0.194444               1          4
12858  0.08   0.319149  0.333333  ...    0.305556               1          1
12861  0.08   0.446809  0.259259  ...    0.305556               1          1
12863  0.04   0.382979  0.419753  ...    0.250000               1          1
12864  0.12   0.234043  0.320988  ...    0.194444               1          4
12865  0.16   0.340426  0.296296  ...    0.194444               1          4
12866  0.12   0.234043  0.345679  ...    0.305556               1          1
1286

In [0]:
df_y = df['Overall'].copy()

In [25]:
df_y.head()

12    89
15    89
24    88
26    88
28    88
Name: Overall, dtype: int64

In [26]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2

chi2_best = SelectKBest(chi2, k=20)

X_ch2 = chi2_best.fit_transform(df_x,df_y)

# this is a relatively strait-forward way to get to two highest indicies
max_indx = pd.Series(np.argsort(chi2_best.scores_), name='score')\
                    .nlargest(n=20).\
                    index.values
        
print('The best features of the chi2 test are:\n')

for i in range(20):
    # the +1 factor is because 
    print('{}. {}'.format(i+1, df_x.columns[max_indx[i] + 1]))

The best features of the chi2 test are:

1. GKReflexes
2. Curve
3. Finishing
4. Potential
5. Crossing
6. ShortPassing
7. HeadingAccuracy
8. SprintSpeed
9. ShotPower
10. Balance
11. Preferred Foot
12. Acceleration
13. Aggression
14. Strength
15. Vision
16. Interceptions
17. GKKicking
18. Agility
19. LongShots
20. BallControl


In [0]:
df_sel_x = df_x[["StandingTackle", "FKAccuracy", "HeadingAccuracy", "Potential", "Finishing", "ShortPassing", "Crossing", "Agility", "Jumping", "Stamina", "GKKicking",     
                "Acceleration", "Composure", "LongShots", "Vision", "Marking", "GKPositioning", "SprintSpeed", "Reactions", "BallControl"]].copy()

In [0]:
X = np.array(df_x)

In [0]:
Y = np.array(df_y)

In [0]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=1 )

In [31]:
#Linear Regression
from sklearn.metrics import mean_squared_error, r2_score
from sklearn import  linear_model

lr = linear_model.LinearRegression()
lr.fit(X_train,Y_train)
lr_pred = lr.predict(X_test)

print ('--------------------------------------------------')
print ('MODEL: Linear Regression')
print ('--------------------------------------------------')


print('Actual values:')
print(Y_test)
print('Predicted values:')
print(lr_pred)

lr_mse  = mean_squared_error(lr_pred, Y_test)
lr_rmse = np.sqrt(lr_mse)
print('RMSE Score for Linear Regression:', lr_mse)
print('R2 Score: %.2f' % r2_score(Y_test, lr_pred))

--------------------------------------------------
MODEL: Linear Regression
--------------------------------------------------
Actual values:
[69 72 76 ... 57 77 65]
Predicted values:
[69.91970131 75.42579114 76.12672033 ... 54.85544654 77.76620057
 64.06445449]
RMSE Score for Linear Regression: 3.4371507032523487
R2 Score: 0.92


In [32]:
ri = Ridge(alpha=0.1, normalize=False).fit(X_train,Y_train)
ri_pred = ri.predict(X_test)
ri_mse  = mean_squared_error(ri_pred, Y_test)
ri_rmse = np.sqrt(ri_mse)

print ('--------------------------------------------------')
print ('MODEL: Ridge')
print ('--------------------------------------------------')
print('Actual values:')
print(Y_test)
print('Predicted values:')
print(ri_pred)
print('RMSE Score for Ridge:',ri_rmse)
print('R2 for Ridge: %.2f' % r2_score(Y_test, ri_pred))

--------------------------------------------------
MODEL: Ridge
--------------------------------------------------
Actual values:
[69 72 76 ... 57 77 65]
Predicted values:
[69.91544107 75.41878208 76.12643978 ... 54.85943497 77.76044729
 64.06382002]
RMSE Score for Ridge: 1.8539469687150731
R2 for Ridge: 0.92


In [33]:
ricv = RidgeCV(cv=5).fit(X_train,Y_train)
ricv_pred = ricv.predict(X_test)
ricv_mse  = mean_squared_error(ricv_pred, Y_test)
ricv_rmse = np.sqrt(ricv_mse)

print ('--------------------------------------------------')
print ('MODEL: RidgeCV')
print ('--------------------------------------------------')
print('Actual values:')
print(Y_test)
print('Predicted values:')
print(ricv_pred)
print('RMSE Score for RidgeCV:',ricv_rmse)
print('R2 for RidgeCV: %.2f' % r2_score(Y_test, ricv_pred))

--------------------------------------------------
MODEL: RidgeCV
--------------------------------------------------
Actual values:
[69 72 76 ... 57 77 65]
Predicted values:
[69.91544107 75.41878208 76.12643978 ... 54.85943497 77.76044729
 64.06382002]
RMSE Score for RidgeCV: 1.8539469687150731
R2 for RidgeCV: 0.92


In [34]:
gdb = GradientBoostingRegressor(n_estimators=200).fit(X_train,Y_train)
gdb_pred = gdb.predict(X_test)
gdb_mse  = mean_squared_error(gdb_pred, Y_test)
gdb_rmse = np.sqrt(gdb_mse)

print ('--------------------------------------------------')
print ('MODEL: Gradient Boosting')
print ('--------------------------------------------------')
print('Actual values:')
print(Y_test)
print('Predicted values:')
print(gdb_pred)
print('RMSE Score for Gradient Boosting:',gdb_rmse)
print('R2 for Gradient Boosting: %.2f' % r2_score(Y_test, gdb_pred))

--------------------------------------------------
MODEL: Gradient Boosting
--------------------------------------------------
Actual values:
[69 72 76 ... 57 77 65]
Predicted values:
[68.16093507 71.5890343  76.81861872 ... 55.82511326 76.98275831
 65.09298557]
RMSE Score for Gradient Boosting: 1.0464339453580653
R2 for Gradient Boosting: 0.98


In [35]:
lasso = Lasso(alpha =0.0005, random_state=10).fit(X_train,Y_train)
lasso_pred = lasso.predict(X_test)
lasso_mse  = mean_squared_error(lasso_pred, Y_test)
lasso_rmse = np.sqrt(lasso_mse)

print ('--------------------------------------------------')
print ('MODEL: Lasso')
print ('--------------------------------------------------')
print('Actual values:')
print(Y_test)
print('Predicted values:')
print(lasso_pred)
print('RMSE Score for Lasso:',lasso_rmse)
print('R2 for Lasso: %.2f' % r2_score(Y_test, lasso_pred))

--------------------------------------------------
MODEL: Lasso
--------------------------------------------------
Actual values:
[69 72 76 ... 57 77 65]
Predicted values:
[69.94029423 75.39551573 76.08327905 ... 54.90991898 77.76694513
 64.01732664]
RMSE Score for Lasso: 1.8519866138180927
R2 for Lasso: 0.92


In [36]:
en = ElasticNet(alpha=0.005, l1_ratio=0.1).fit(X_train,Y_train)
en_pred = en.predict(X_test)
en_mse  = mean_squared_error(en_pred, Y_test)
en_rmse = np.sqrt(en_mse)

print ('--------------------------------------------------')
print ('MODEL: Elastic Net')
print ('--------------------------------------------------')
print('Actual values:')
print(Y_test)
print('Predicted values:')
print(en_pred)
print('RMSE Score for Elastic Net:',en_rmse)
print('R2 for Elastic Net: %.2f' % r2_score(Y_test, en_pred))

--------------------------------------------------
MODEL: Elastic Net
--------------------------------------------------
Actual values:
[69 72 76 ... 57 77 65]
Predicted values:
[69.16393756 73.85193051 75.51893219 ... 56.00077052 76.08816376
 63.78907886]
RMSE Score for Elastic Net: 2.0446546400201777
R2 for Elastic Net: 0.90


In [37]:
xgb = xgb.XGBRegressor(objective ='reg:linear', colsample_bytree = 0.5, learning_rate = 0.1,
                max_depth = 3, alpha = 10, n_estimators = 10000).fit(X_train,Y_train)
xgb_pred = xgb.predict(X_test)
xgb_mse  = mean_squared_error(xgb_pred, Y_test)
xgb_rmse = np.sqrt(xgb_mse)

print ('--------------------------------------------------')
print ('MODEL: XGBoost')
print ('--------------------------------------------------')
print('Actual values:')
print(Y_test)
print('Predicted values:')
print(xgb_pred)
print('RMSE Score for XGBoost:',xgb_rmse)
print('R2 for XGBoost: %.2f' % r2_score(Y_test, xgb_pred))

[17:14:28] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
--------------------------------------------------
MODEL: XGBoost
--------------------------------------------------
Actual values:
[69 72 76 ... 57 77 65]
Predicted values:
[68.6717   71.55141  76.74771  ... 56.550507 77.16396  64.928825]
RMSE Score for XGBoost: 0.8115092136922504
R2 for XGBoost: 0.99


In [38]:
br = linear_model.BayesianRidge().fit(X_train,Y_train)
br_pred = br.predict(X_test)
br_mse  = mean_squared_error(br_pred, Y_test)
br_rmse = np.sqrt(br_mse)

print ('--------------------------------------------------')
print ('MODEL: Bayesian Ridge')
print ('--------------------------------------------------')
print('Actual values:')
print(Y_test)
print('Predicted values:')
print(br_pred)
print('RMSE Score for Bayesian Ridge:',br_rmse)
print('R2 for Bayesian Ridge: %.2f' % r2_score(Y_test, br_pred))

--------------------------------------------------
MODEL: Bayesian Ridge
--------------------------------------------------
Actual values:
[69 72 76 ... 57 77 65]
Predicted values:
[69.91414393 75.41664557 76.12634903 ... 54.86065325 77.75868892
 64.06362434]
RMSE Score for Bayesian Ridge: 1.8539463571603967
R2 for Bayesian Ridge: 0.92


In [39]:
df.head()

ID             Name   Age  ... GKReflexes  Release Clause  pozicija
12  189511  Sergio Busquets  0.52  ...   0.333333         €105.6M         V
15  138956     G. Chiellini  0.68  ...   0.055556          €44.6M         B
24  188567    P. Aubameyang  0.52  ...   0.222222         €112.1M         V
26  173731          G. Bale  0.48  ...   0.138889           €123M         N
28  164240     Thiago Silva  0.68  ...   0.250000          €44.4M         B

[5 rows x 86 columns]